baseURL = "https://hellikandra.github.io/LearnWinTAK"
# baseURL = 'http://localhost:1313/LearnWinTAK/"
languageCode = 'en-us'
title = 'WinTAK Documentation'

[module]
    [[module.imports]]
        path = "lotusdocs" # as command-line : git submodule add https://github.com/colinwilson/lotusdocs themes/lotusdocs
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[params.docs] # Parameters for the /docs 'templates'
    #pathName   = "docs"                                    # path name for documentation site | default "docs"
    themeColor = "emerald"                                  # (optional) - Set theme accent colour. Options include: blue (default), green, red, yellow, emerald, cardinal, magenta, cyan
    darkMode   = true                                       # (optional) - Enable dark mode option, default false. Options include: true, false
    prism      = true                                       # (optional) - Enable syntax highlighting via Prism. Options include: true, false

    # gitinfo
    ghrepo          = "https://github.com/Hellikandra/LearnWinTAK"  # Git repository URL for your site
    editPage        = true                                  # enable 'Edit this page' feature - default false
    lastMod         = true                                  # enable 'Last modified' date on pages - default false
    lastModRelative = true                                  # format 'Last modified' time as relative - default true

    sidebarIcons    = true                                  # enable sidebar icons? default false
    breadcrumbs     = true                                  # default is true
    backToTop       = true                                  # enable back-to-top button? default true

    # ToC
    toc             = true                                  # enable table of contents? default is true
    tocMobile       = true                                  # enable table of contents in mobile view? default is true
    scrollSpy       = true                                  # enable scrollspy on ToC? default is true

    # front matter
    descriptions    = true                                  # enable front matter descriptions under content title?
    titleIcon       = true                                  # enable front matter icon title prefix? default is false

    # content navigation
    navDesc         = true                                  # include front matter descriptions in Prev/Next navigation cards
    navDescTrunc    = 30                                    # Number of characters by which to truncate the Prev/Next descriptions

    listDescTrunc   = 100                                   # Number of characters by which to truncate the list card description

[menu]
[[menu.primary]]
    name = "Documentation"
    url = "docs/"
    identifier = "docs"
    weight = 10